name: 'Pull from BB into GH'
description: 'Takes a pull from bitbucket repo into github repo.'
inputs:
  ssh-key:
    description: 'SSH Key.'
    default: ''
    required: true
  bitbucket-repo:
    description: 'Bitbucket repository.'
    default: ''
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SSH_KEY: ${{ inputs.ssh-key }}
    BITBUCKET_REPO : ${{ inputs.bitbucket-repo }}