name: 'Basic Custom Action'
description: 'This is basic Custom workflow file that executes a Python script.'
inputs:
  var-1:
    description: 'Dummy environment variable.'
    default: ''
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    VAR_1: ${{ inputs.var-1 }}