name: 'Basic Custom Action'
description: 'This is basic Custom workflow file that executes a Python script.'
inputs:
  message:
    description: 'Dummy environment variable.'
    default: ''
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    MY_MESSAGE: ${{ inputs.message }}