name: 'PR Feedback'
description: 'Takes Feedback from LLM reagrding the PR created.'
inputs:
  project-id:
    description: 'The id of the GCP Project.'
    default: ''
    required: true
  location:
    description: 'The location of the GCP Project.'
    default: ''
    required: true
  google-api-key:
    description: 'The API key.'
    default: ''
    required: true
  google-application-credentials:
    description: 'The service account key.'
    default: ''
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PROJECT_ID: ${{ inputs.project-id}}
    LOCATION: ${{ inputs.location }}
    GOOGLE_API_KEY: ${{ inputs.google-application-credentials }}
    GOOGLE_APPLICATION_CREDENTIALS: ${{ inputs.google-application-credentials }}
