name: 'PR Feedback'
description: 'Takes Feedback from LLM reagrding the PR created.'
inputs:
  pr-title:
    description: 'The title of the PR'
    required: true
  issue-number:
    description: 'The number of the issue'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PR_TITLE: ${{ inputs.pr-title }}
    ISSUE_NUMBER: ${{ inputs.issue-number }}