name: 'PR Feedback'
description: 'Takes Feedback from LLM reagrding the PR created.'
inputs:
  project-id:
    description: 'The id of the GCP Project.'
    default: ''
    required: true
  location:
    description: 'The location of the GCP Project.'
    default: ''
    required: true
  ai-studio-api-key:
    description: 'The API key for AI Studio.'
    default: ''
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PROJECT_ID: ${{ inputs.project-id}}
    LOCATION: ${{ inputs.location }}
    AI_STUDIO_API_KEY: ${{ inputs.ai-studio-api-key }}
