name: 'PR Feedback'
description: 'Takes Feedback from LLM reagrding the PR created.'
inputs:
  git-token:
    description: 'The token for the git to post comment.'
    default: ''
    required: true
  repo-url:
    description: 'The URL of the repository.'
    default: ''
    required: true
  issue-number:
    description: 'The issue number of the PR.'
    default: ''
    required: true
  ai-studio-api-key:
    description: 'The API key for AI Studio.'
    default: ''
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GIT_TOKEN: ${{ inputs.git-token }}
    REPO_URL: ${{ inputs.repo-url }}
    ISSUE_NUMBER: ${{ inputs.issue-number }}
    AI_STUDIO_API_KEY: ${{ inputs.ai-studio-api-key }}
